QUALITIES = {
    "default": 'SD',
    'symbols': ['[', ']', '(', ')', '{', '}'],
    "names": ['SD', 'HD', 'FHD', 'QHD', 'UHD'],
    # Reversed because in higher qualities more words
    "aliases": {
        'UHD': [
            "uhd",
            "4k",
            "8k",
            ["ultra", "hd"]
        ],
        'QHD': [
            "qhd",
            "2k",
            "1440p",
            ["quad", "hd"]
        ],
        'FHD': [
            "fhd",
            "1080p",
            ["full", "hd"]
        ],
        'HD': [
            "hd",
            "720p"
        ]
    }
}

THEMES = {
  "default": None,
  "themes": {
    "": [],
    "Деловые": [
      "рбк",
      "cc 2",
      "cc 3",
      "cnbc",
      "cnbc asia",
      "cnbc europe"
    ],
    "Детские": [
      "4kids",
      "4multimania",
      "балапан",
      "бибигон",
      "детский мир",
      "карусель",
      "мульт",
      "пиксель",
      "радость моя",
      "стс kids",
      "плюсплюс",
      "тлум hd",
      "boomerang",
      "canal j",
      "cartoon network",
      "disney channel",
      "disney cinemagic",
      "disney junior",
      "disney xd",
      "fox kids",
      "gulli",
      "jetix",
      "jimjam",
      "kids station",
      "kika",
      "lâle",
      "nickelodeon",
      "nicktoons",
      "spacetoon",
      "super rtl",
      "super7",
      "teenick",
      "teletoon",
      "tiji",
      "toon disney",
      "land"
    ],
    "Информация": [
      "а1+",
      "астрахань 24",
      "беларусь 24",
      "вместе рф",
      "коммерсантъ",
      "москва 24",
      "рбк",
      "россия 24",
      "телеканал 16/12",
      "урфо 24",
      "хабар 24",
      "царьград",
      "эксперт",
      "armnews",
      "cgtn",
      "channel newsasia",
      "cnbc",
      "cnbc asia",
      "cnbc europe",
      "cnn",
      "cnn international",
      "euronews",
      "kazakh",
      "life",
      "msnbc",
      "n",
      "news7",
      "n",
      "one news",
      "polsat news",
      "polsat news 2",
      "polsat sport news",
      "rt",
      "rt español",
      "rt uk",
      "ta3",
      "patriot",
      "nz 7",
      "ubr",
      "uzreport",
      "welt"
    ],
    "Музыка": [
      "9 волна",
      "дар 21",
      "лайм",
      "м1",
      "м2",
      "ммс",
      "муз",
      "музыка первого",
      "н плюс музыка",
      "о2",
      "планета",
      "тнт music",
      "туркмен овазы",
      "шахнавоз",
      "a one",
      "acb",
      "clubbing",
      "country music television",
      "dancetrippin",
      "eu music",
      "europa plus",
      "fuse",
      "hit",
      "lux",
      "mad",
      "mcm",
      "mezzo",
      "mnet",
      "m россия",
      "m украина",
      "m dance",
      "m europe",
      "m live hd",
      "m uk",
      "muzzone",
      "o",
      "ru",
      "trace urban",
      "u",
      "vh1",
      "vh1 россия",
      "viva",
      "viva polska",
      "zor"
    ],
    "Парламентские": [
      "вместе рф",
      "рада",
      "собраниски канал",
      "bbc parliament",
      "phoenix"
    ],
    "Познавательные": [
      "24 док",
      "365 дней",
      "беларусь 2",
      "беларусь 3",
      "білім және мәдениет",
      "война и мир",
      "еда",
      "кто есть кто",
      "мама",
      "моя планета",
      "наука",
      "охотник и рыболов",
      "приключения hd",
      "психология 21",
      "совершенно секретно",
      "техно 24",
      "шогакат",
      "animal planet",
      "da vinci",
      "discovery channel",
      "discovery hd showcase",
      "discovery world",
      "dr k",
      "history channel",
      "investigation discovery",
      "kazakh",
      "lux",
      "nat geo wild",
      "national geographic",
      "outdoor channel",
      "rambler телесеть",
      "russian travel guide",
      "science channel",
      "the biography channel",
      "viasat explore",
      "yle teema"
    ],
    "Развлекательные": [
      "2x2",
      "31 канал",
      "домашний",
      "пятница!",
      "синема",
      "совершенно секретно",
      "супер",
      "тнт4",
      "ю",
      "a",
      "canal j",
      "clubbing",
      "diva universal",
      "dr3",
      "е!",
      "fashion",
      "kabel eins",
      "lux",
      "luxe",
      "milliy",
      "my5",
      "paramount channel",
      "rtl zwei",
      "sony sci fi",
      "teenick",
      "tlc",
      "viva",
      "zor"
    ],
    "Спорт": [
      "2 спорт 2",
      "беларусь 2",
      "беларусь 5",
      "варзиш",
      "ктрк спорт",
      "кхл",
      "матч премьер",
      "матч",
      "матч! арена",
      "матч! игра",
      "матч! страна",
      "матч! футбол 1",
      "матч! футбол 2",
      "матч! футбол 3",
      "н плюс баскетбол",
      "н плюс спорт",
      "н плюс спорт онлайн",
      "н плюс спорт союз",
      "н плюс теннис",
      "н плюс nba",
      "олимпийская вещательная служба",
      "планета спорт",
      "реал мадрид",
      "россия 2",
      "семёрка",
      "спартак",
      "список спортивных телеканалов мира",
      "футбол",
      "футбол 1",
      "футбол 2",
      "acb",
      "bt sport",
      "eurosport",
      "eurosport 1",
      "eurosport 2",
      "hd спорт",
      "mu",
      "nba",
      "polsat sport",
      "polsat sport extra",
      "polsat sport news",
      "premier sports",
      "ring",
      "setanta sports",
      "sky sport",
      "sky sports",
      "sport",
      "sport7",
      "turkmenistan sport",
      "uzreport",
      "viasat sport",
      "xsport"
    ],
    "Общие": [
      "la 1",
      "1 й канал останкино",
      "1+1",
      "2+2",
      "4 й канал останкино",
      "31 канал",
      "армения 2",
      "беларусь 1",
      "вторая программа цт",
      "звезда",
      "интер",
      "ктк",
      "македония",
      "мир",
      "московская программа цт",
      "московский телевизионный канал",
      "н",
      "н беларусь",
      "нтн",
      "онт",
      "первая программа цт",
      "первый канал «евразия»",
      "пятый канал",
      "рен",
      "россия 1",
      "седьмой канал",
      "си би эс",
      "стб",
      "с",
      "с",
      "таджикистан",
      "сафина",
      "центр",
      "6",
      "і",
      "с",
      "тонис",
      "украина",
      "хабар",
      "хазар",
      "чеёртая программа цт",
      "эра",
      "alpha",
      "american broadcasting company",
      "ant1",
      "antena 3",
      "asyl arna",
      "az",
      "canale 5",
      "cuatro",
      "diyor",
      "fox broadcasting company",
      "gms",
      "ic",
      "i",
      "jednotka",
      "m6",
      "mega channel",
      "nbc",
      "new greek",
      "polsat",
      "public broadcasting service",
      "qazaqstan",
      "rtl television",
      "sat 1",
      "lasexta",
      "sic",
      "skai",
      "telecinco",
      "tf1",
      "the cw television network",
      "nova",
      "3",
      "3",
      "4",
      "vox"
    ],
    "Фильмы": [
      "кинопоказ",
      "киносвидание",
      "кинохит",
      "комедийное",
      "родное кино",
      "русский иллюзион",
      "синамо",
      "синема",
      "супер",
      "3",
      "телеклуб",
      "diva universal",
      "enter фильм",
      "syfy universal",
      "tcm",
      "1000",
      "1000 русское кино",
      "universal",
      "rai movie",
      "rai premium",
      "one piece  большой куш"
    ],
    "Футбол": [
      "матч премьер",
      "матч! футбол 1",
      "матч! футбол 2",
      "матч! футбол 3",
      "футбол",
      "футбол",
      "футбол 1",
      "футбол 2",
      "futbol"
    ],
    "Юмор": [
      "тнт4",
      "comedy central",
      "comedy"
    ]
  }
}